version: '3'

services:
  server:
      container_name: PARTNER_MANAGER_TEST
      build:
        context: '.'
        dockerfile: Dockerfile.test
      volumes:
        - ./:/partner-manager
        - ./node_modules:/partner-manager/node_modules
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: root  
      depends_on:
        - mongo-test
      networks:
      - mongo-compose-network
      ports:
        - '3000:3000'

  mongo-test:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27018:27017"
    volumes:
      - /Users/murilosantos/Documents/docker-test/data
    networks:
      - mongo-compose-network

networks: 
    mongo-compose-network:
      driver: bridge
